# ============================================================================
# ChatGPT Diagnostic Accuracy Study - Data Import
# ============================================================================
# Purpose: Load pre-generated synthetic data for analysis
# Note: Data generated by 00_generate_synthetic_data.R
# ============================================================================

# Source setup
source(here::here("projects", "chatgpt_diagnostic_study", "scripts", "00_setup.R"))

# ============================================================================
# 1. Load processed data
# ============================================================================

cases_file <- file.path(data_processed, "chatgpt_cases_cleaned.csv")
reviews_file <- file.path(data_processed, "all_reviews.csv")
diagnostic_file <- file.path(data_processed, "diagnostic_accuracy_600.csv")

# Check if data exists, if not generate it
if (!file.exists(cases_file)) {
  cat("Data not found. Running 00_generate_synthetic_data.R...\n")
  source(here::here("projects", "chatgpt_diagnostic_study", "scripts", "00_generate_synthetic_data.R"))
}

# Load data
cases_cleaned <- read_csv(cases_file, show_col_types = FALSE)
all_reviews <- read_csv(reviews_file, show_col_types = FALSE)
diagnostic_data <- read_csv(diagnostic_file, show_col_types = FALSE)

# ============================================================================
# 2. Summary
# ============================================================================

cat("=== Data Loaded ===\n\n")

cat("Cases dataset:\n")
cat("  Total cases:", nrow(cases_cleaned), "\n")
cat("  Correct:", sum(cases_cleaned$answer_correct_bool), "\n")
cat("  Accuracy:", round(mean(cases_cleaned$answer_correct_bool) * 100, 1), "%\n\n")

cat("Cognitive Load distribution:\n")
print(table(cases_cleaned$cognitive_load_std))

cat("\nQuality distribution:\n")
print(table(cases_cleaned$quality_answer_std))

cat("\nDiagnostic Accuracy (600 responses):\n")
print(table(diagnostic_data$diagnostic_result))

# ============================================================================
# 3. Validation against paper values
# ============================================================================

cat("\n=== Validation Against Paper ===\n")

n_correct <- sum(cases_cleaned$answer_correct_bool)
n_total <- nrow(cases_cleaned)
pct_correct <- n_correct / n_total * 100

cat(sprintf("Correct answers: %d / %d (%.1f%%)\n", n_correct, n_total, pct_correct))
cat("Paper reported: 74 / 150 (49.3%)\n")

if (abs(pct_correct - 49.3) < 1) {
  cat("✓ Matches paper value\n")
} else {
  cat("⚠ Deviation from paper value\n")
}
